### ISSUE TITLE
Laterst version (came with second version of 5.11) breaks intel ax210 wifi

### ISSUE THREAD

**Issue by spxak1** [pop-os/linux-firmware#8] opened 2021-04-02 20:36 UTC
System:
~~~
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
~~~
~~~
# uname -a
Linux weywot 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
~~~

The first upgrade to 5.11 (1616168001) worked fine. Both Wifi and BT of the intel ax210 worked.
The second version of 5.11 (1617215757) came with linux-firmware that broke the Wifi (BT still works fine).

This is the output of ```dmesg | grep iwlwifi```
~~~
[    4.821922] iwlwifi 0000:03:00.0: enabling device (0000 -> 0002)
[    4.833552] iwlwifi 0000:03:00.0: api flags index 2 larger than supported by driver
[    4.833570] iwlwifi 0000:03:00.0: TLV_FW_FSEQ_VERSION: FSEQ Version: 93.8.63.28
[    4.833910] iwlwifi 0000:03:00.0: loaded firmware version 59.601f3a66.0 ty-a0-gf-a0-59.ucode op_mode iwlmvm
[    4.886547] iwlwifi 0000:03:00.0: Detected Intel(R) Wi-Fi 6 AX210 160MHz, REV=0x420
[    5.055367] iwlwifi 0000:03:00.0: loaded PNVM version 0x324cd670
[    5.157342] iwlwifi 0000:03:00.0: Timeout waiting for PNVM load!
[    5.166031] iwlwifi 0000:03:00.0: Failed to start RT ucode: -110
[    5.174923] iwlwifi 0000:03:00.0: iwl_trans_send_cmd bad state = 1
[    5.384914] iwlwifi 0000:03:00.0: firmware didn't ACK the reset - continue anyway
[    5.413064] iwlwifi 0000:03:00.0: Failed to run INIT ucode: -110
~~~

This is the exam same issue reported in here ([arch link)[https://bugs.archlinux.org/task/70071]).

I am currently trying to revert to the previous firmware version. I will report back.

**Comment by jackpot51** [comment] 2021-04-02 20:44
Can you confirm this fix?

https://bugzilla.kernel.org/show_bug.cgi?id=212371#c13

**Comment by spxak1** [comment] 2021-04-02 20:59
> Can you confirm this fix?
> 
> https://bugzilla.kernel.org/show_bug.cgi?id=212371#c13

I will try asap.

For the moment I can say that I tried **20210315** and **20210208** from https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git.

The former (newer) causes the issue above, the latter (older) fixes it.

I will try the workaround suggested now.

**Comment by spxak1** [comment] 2021-04-02 21:03
> Can you confirm this fix?
> 
> https://bugzilla.kernel.org/show_bug.cgi?id=212371#c13

The workaround works. Using the pop provided linux-firmware package and removing  ```iwlwifi-ty-a0-gf-a0.pnvm``` restores the wifi. 

Thank you.

**Comment by spxak1** [comment] 2021-04-02 21:12
For what it's worth, this is the output of ```lspci```

```03:00.0 Network controller: Intel Corporation Device 2725 (rev 1a)```

I think the mainline 5.11 has a better name for it. Not important, but I just add it here.

**Comment by eliasfarah** [comment] 2021-04-06 19:39
The workaround works for me too, thanks!

**Comment by jackpot51** [comment] 2021-04-06 21:01
I have applied the workaround here: https://github.com/pop-os/linux-firmware/pull/11

We don't have the AX210 in-house, but we do have a number of other Intel WiFi cards to test with. If there are no regressions, this workaround will be released

**Comment by spxak1** [comment] 2021-04-06 21:31
> I have applied the workaround here: #11
> 
> We don't have the AX210 in-house, but we do have a number of other Intel WiFi cards to test with. If there are no regressions, this workaround will be released

Others on reddit with the same issue have also verified the workaround works without any side effects. Thank you for your time.

**Comment by jackpot51** [comment] 2021-04-08 14:05
Can it be confirmed that linux-firmware 1.196+system76~1617760239~21.04~be8660e fixes this issue?

**Comment by eliasfarah** [comment] 2021-04-08 14:40
Yes, working good Intel AX210 =)

```
farah@pop-os:~$ sudo apt-cache policy linux-firmware
Installed: 1.196+system76~1617760239~20.10~be8660e
```

```
farah@pop-os:~$ uname -a
Linux pop-os 5.11.0-7612-generic #13~1617215757~20.10~97a8d1a-Ubuntu SMP Thu Apr 1 21:09:17 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

```

**Comment by jackpot51** [comment] 2021-04-08 14:43
Thanks, will close this now

**Closed by jackpot51** 2021-04-08 14:43 UTC
